# Pre-commit hooks configuration
# See https://pre-commit.com for more information

repos:
  # Hooks gerais do pre-commit
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        name: Remove espaços em branco no final das linhas
      - id: end-of-file-fixer
        name: Garante nova linha no final dos arquivos
      - id: check-yaml
        name: Valida sintaxe de arquivos YAML
      - id: check-json
        name: Valida sintaxe de arquivos JSON
      - id: check-added-large-files
        name: Previne commit de arquivos grandes
        args: ['--maxkb=1000']
      - id: check-merge-conflict
        name: Verifica marcadores de conflito de merge
      - id: check-ast
        name: Valida sintaxe Python (AST)
      - id: debug-statements
        name: Detecta statements de debug (pdb, ipdb)

  # Formatação de código Python com Black
  - repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
      - id: black
        name: Formatação de código com Black
        language_version: python3
        args: ['--line-length=100']

  # Ordenação de imports
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: Ordenação de imports com isort
        args: ['--profile', 'black', '--line-length', '100']

  # Linting com flake8
  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        name: Linting de código com flake8
        args: ['--max-line-length=100', '--extend-ignore=E203,W503']

  # Hook local para testes e coverage
  - repo: local
    hooks:
      - id: django-tests
        name: Executar testes Django
        entry: python3 manage.py test problems.tests --verbosity=1
        language: system
        pass_filenames: false
        always_run: true
        stages: [commit]

      - id: coverage-check
        name: Verificar cobertura de testes (mínimo 70%)
        entry: bash -c 'coverage run --source=. manage.py test problems.tests && coverage report --fail-under=70'
        language: system
        pass_filenames: false
        always_run: true
        stages: [commit]

